### ISSUE TITLE
model parameters in optimizer

### ISSUE THREAD

**Issue by tymatfd** [Jia-Research-Lab/PFENet#10]
Hello , Thank you for the excellent work. I noticed that when setting optimizer ,modules in the model are all separately listed while backbone layers' require_grad are already set False. Why not use model.parameters instead,  will it influence the training procedure ?

**Comment by tianzhuotao** [comment]
Hi @tymatfd,

In our model, only the backbone is fixed and the FEM and classification head require gradients to be updated, therefore we need to fix each module specifically rather than using the 'model.parameters' that fixes all parameters in the model.

Thank you.

**Comment by tymatfd** [comment]
> Hi @tymatfd,
> 
> In our model, only the backbone is fixed and the FEM and classification head require gradients to be updated, therefore we need to fix each module of the backbone specifically rather than using the 'model.parameters' that fixes all parameters in the model.
> 
> As for your question, I did not test whether the performance would be affected by sending model.parameters to the optimizer. I did in that way is only to be on the safe side.
> 
> You can share the results with us if you have done this comparison.
> 
> Thank you.

Thanks for your reply. I have done some comparisons by so far, seems nothing have changed. I will do more experiments to verify this.
