### ISSUE TITLE
how to generate SegmentationClassAug？

### ISSUE THREAD

**Issue by ily666666** [Jia-Research-Lab/PFENet#15]
I have downloaded the PASCAL VOC 2012 dataset and SBD dataset from  their official website respectively.But I donnot know how   to use them in the code .Could you show me your dataset folder structure or the method to generate SegmentationClassAug?
Thanks , bubble from hfut!

**Comment by tianzhuotao** [comment]
@ily666666 

Hi, thank you for being interested in our work.  

I have replied to the email with the pre-processed dataset. Please check the inbox.

**Comment by cql980603** [comment]
> @ily666666
> 
> Hi, thank you for being interested in our work.
> 
> I have replied to the email with the pre-processed dataset. Please check the inbox.

could you please also provide me with the pre-processed dataset?

**Comment by WHL182** [comment]
could you please also provide me with the pre-processed dataset?

**Comment by vangjin** [comment]
I have met the same problem, could you please provide me with the pre-processed dataset?

**Comment by KangLeeShaw** [comment]
Help! I also need the pre-processed dataset. My email is Kangnniexiao@163.com
