### ISSUE TITLE
Which setting do the pre-trained VGG16 models on COCO follow?

### ISSUE THREAD

**Issue by zhiheLu** [Jia-Research-Lab/PFENet#18]
From your paper, we know there two settings for COCO, from PANet and FWBF, respectively. So, for the pre-trained models you give, which setting you are using?

**Comment by tianzhuotao** [comment]
@zhiheLu  

Thanks for being interested in our work. 

The pre-trained model follows the configuration file we provide in this repo. Therefore you can directly test it with https://github.com/Jia-Research-Lab/PFENet/blob/master/config/coco/coco_split0_vgg.yaml.

As for different settings, we provide the model with FWBF setting. If you want to train/test with the PANet COCO setting, you can simply set the option "use_split_coco" to false.
