### ISSUE TITLE
COCO2014 dataset label

### ISSUE THREAD

**Issue by Hardcandies** [Jia-Research-Lab/PFENet#20]
Hi!

 I notice that you used a *.png for COCO2014 label images. Can you provide one?

I'm trying to do it myself, and I find that when I convert from JSON of COCO's anotations to an image, one pixel corresponds to multiple category. How can I handle this situation to ensure that I get the same results as you?

**Comment by tianzhuotao** [comment]
@Hardcandies Hi, you can use the parsing script we provide at https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/ETkX1jKVuJpAjpS2dk8XRhgBxkOUregKv4C7zigqFXiEtQ.

**Comment by tianzhuotao** [comment]
@Hardcandies  To get the same results, you can test with the pre-trained models we provide in this repo :)

**Comment by Hardcandies** [comment]
Thank!

**Comment by JC-chen97** [comment]
Hi, I noticed that the script of this link was modified on 2021/6/21. Now I use this modified script to generate the label image of coco, which is different from that generated before. Is there something wrong with me or the modified script? Can you provide a previous version? Thanks!

**Comment by JJ-res101** [comment]
Hi, I noticed that the script of this link was modified on 2021/6/21. Now I use this modified script to generate the label image of coco, which is different from that generated before. Is there something wrong with me or the modified script? Can you provide a previous version that you used before? Thanks!
