### ISSUE TITLE
The SBD dataset

### ISSUE THREAD

**Issue by luckybeanss** [Jia-Research-Lab/PFENet#21]
Hi，I want to know how to get the SBD class segmentation masks. The data I downloaded from http://home.bharathh.info/pubs/codes/SBD/download.html only contains segmentation information in mat format.

**Comment by tianzhuotao** [comment]
Thanks for being interested in our work.

The pre-processed Pascal-VOC ground-truth files can be download from [**gt_voc.zip**](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/ERgySoNYb7hBqvDBE8z4qVsBh6u3KiWNBYDYBMeg1zgEKA).

**Comment by luckybeanss** [comment]
Thanks for your help. It is worth mentioning that I also encountered this problem on the COCO dataset, but still did not find a solution, can you tell me how to find the segmentation mask for COCO.

**Comment by tianzhuotao** [comment]
@luckybeanss 

Sorry for my late reply. You can use this script to generate COCO labels. 

https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/ETkX1jKVuJpAjpS2dk8XRhgBxkOUregKv4C7zigqFXiEtQ.
