### ISSUE TITLE
Experiment detail

### ISSUE THREAD

**Issue by 2448845600** [Jia-Research-Lab/PFENet#24]
Hi, this project is very helpful. But I would like to know some details:
1. the backbone you provided named resnet50_v2,pth and resnet101_v2.pth. Did you train this backbone from init for few-shot segmentation task?
2. I get same result with pre-trained model. But the model training by myself is lower about 2% mIoU. Is the config same with the paper setting?

Thanks.

**Comment by tianzhuotao** [comment]
@2448845600

The two pre-trained backbones are directly provided by the author of [PSPNet ](https://github.com/hszhao/semseg), and we did not tune them specifically for the few-shot segmentation task. You can find the same checkpoints at [**this cite**](https://drive.google.com/open?id=15wx9vOM0euyizq-M1uINgN0_wjVRf9J3).

For the reproduction issue, we have found that different experimental environments cause performance variance. The reproduced details can be found in this [**issue**](https://github.com/Jia-Research-Lab/PFENet/issues/6).

With the same python dependencies/environments, this repo can achieve better performance than that reported in our paper.

**Comment by 2448845600** [comment]
Hi, I reproduce the results now, thanks! The results is close to your paper when I use single-gpu(1*3090), However, if I use multi-gpu(4*3090), the mIoU is lower about 2%.
Could you please give me some ideas about multi-gpu?

**Comment by tianzhuotao** [comment]
@2448845600 

We did not implement the multi-GPU training therefore the BN layers should be replaced with the sync-BN layers for your case.

You can take references from either PyTorch tutorial of the official implementation of [PSPNet](https://github.com/hszhao/semseg) that our code was built upon.

**Comment by 2448845600** [comment]
Thanks!
