### ISSUE TITLE
Question regarding evaluation with ignore_label

### ISSUE THREAD

**Issue by juhongm999** [Jia-Research-Lab/PFENet#25]
Hello, I have a question regarding evaluation

In line 52-64 in PFENet/util/util.py (function intersectionAndUnion), the function computes intersection & union between gt-mask and predicted mask. I found that the code uses ignore_label=255, to **refine the prediction** right before computing the intersection & union. Why did you adopt this kind of refinement process (using mask boundary, e.g., ignore_label)?

This refinement would make sense if the code tries to ignore the zero-padded regions (which is set to ignore_label, e.g., 255) in both predicted and gt masks. However, because the object boundary is also set as ignore_label=255, the prediction is further refined.

In the paper, the mIoU of PFENet in 1-shot setting (with resnet50 backbone) is 60.8% on PASCAL-5i dataset but when I reproduced the model without using object boundary (ignore label), the mIoU drops to 56.2%. May I ask why did you adopt such prediction refinement using gt boundary?

![a](https://user-images.githubusercontent.com/41140817/104724508-1714e400-5774-11eb-9a7a-853ed2da1d4f.png)

I brought example predictions: Top image visualizes naive prediction by the model while the bottom image visualizes refined prediction using gt-boundary.

**Comment by tianzhuotao** [comment]
@juhongm999  

Thanks for being interested in our work.

The 255 annotations are available in the ground-truth files, which is actually one convention of the normal semantic segmentation task on PASCAL-VOC. You can check with the configurations of PSPNet and DeepLab that both use 255 to ignore the boundary regions on Pascal-VOC. But the boundary is not ignored on other segmentation datasets such as COCO, ADE20K and Cityscapes.

As for the few-shot segmentation task, PANet, PPNet and some other recent few-shot segmentation methods are also evaluated on the annotations of PASCAL-5i where boundary regions are ignored. But on COCO-20i, the boundary regions count for the mIoU performance.

Hope this explains your questions.

Thank you~

**Comment by juhongm999** [comment]
Thanks for your quick reply.
Actually I was aware of the fact that there already exists a common IoU evaluation scheme (which uses gt boundary to refine prediction) in task of semantic segmentation.
I was simply curious why most models adopt such scheme.
Do you know why..?

**Comment by tianzhuotao** [comment]
@juhongm999 

Uhhhh.... I guess the ambiguity on the boundary region causes difficulties for models to well generalize, therefore  Pascal VOC adopts it as one of the criteria for a fairer evaluation.

If you have found a better explanation please share it with me.  :)

Thank you~

**Comment by juhongm999** [comment]
I've tried to find documentation about official segmentation evaluation scheme but wasn't able to find one.
Meanwhile, i came up with unofficial one from NVIDIA: https://github.com/NVIDIA/DIGITS/blob/master/examples/semantic-segmentation/pascal-voc-classes.txt

If you have any official sources, would you please share with me?
Thanks for your quick replies !

**Comment by tianzhuotao** [comment]
@juhongm999 Our project was built upon the early version of the official implementation of [PSPNet](https://github.com/hszhao/semseg), from which you can take a reference. 

For other popular implementations, you can refer to [mmseg](https://mmsegmentation.readthedocs.io/en/latest/dataset_prepare.html) that is a comprehensive repo of segmentation models that adopts a similar evaluation method on PASCAL VOC.
