### ISSUE TITLE
About ImageNet pertained model for resnet50

### ISSUE THREAD

**Issue by 1144181135** [Jia-Research-Lab/PFENet#26]
I download the pertained ResNet50 from "https://download.pytorch.org/models/resnet50-19c8e357.pth" and load in the model, there are some mismatch for conv1 and layer1. Can you provide your ImageNet pretrained ResNet50 which is "/data-nas/lyx/FSS/pretrained/resnet50_v2.pth"?

**Comment by tianzhuotao** [comment]
@1144181135 
Hi,

You can download the ImageNet pre-trained models from [google drive](https://drive.google.com/drive/folders/1Hrz1wOxOZm4nIIS7UMJeL79AQrdvpj6v) that are the ones used in [PSPNet](https://github.com/hszhao/semseg).

**Comment by 1144181135** [comment]
> @1144181135
> Hi,
> 
> You can download the ImageNet pre-trained models from [google drive](https://drive.google.com/drive/folders/1Hrz1wOxOZm4nIIS7UMJeL79AQrdvpj6v) that are the ones used in [PSPNet](https://github.com/hszhao/semseg).

After loading from the pretrained model in google drive, it seem like the channel mismatch for conv3. The conv3 in your code is of channel 128, but the pertained model maybe 64. Is there any change in this part?

**Comment by 1144181135** [comment]
> @1144181135
> Hi,
> 
> You can download the ImageNet pre-trained models from [google drive](https://drive.google.com/drive/folders/1Hrz1wOxOZm4nIIS7UMJeL79AQrdvpj6v) that are the ones used in [PSPNet](https://github.com/hszhao/semseg).

Thanks. But after loading from the model in the google drive, there are some mismatch of channels:

  File "/home/wulonglyx/fss-main/PFENet/model/resnet.py", line 78, in forward
    out = self.conv1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 128, 1, 1], expected input[1, 64, 119, 119] to have 128 channels, but got 64 channels instead
