### ISSUE TITLE
What does the "split" means

### ISSUE THREAD

**Issue by 9p15p** [Jia-Research-Lab/PFENet#28]
In README
```
Update the config file by speficifying the target split and path (weights) for loading the checkpoint.
```

what does the split means ?
What role does 'split' play in the program?
e.g
```
assert args.split in [0, 1, 2, 3, 999]
```
Thank you .

**Comment by tianzhuotao** [comment]
@9p15p 

The term Split refers to the data split we mentioned in our paper.

For example, for data split 0, classes 1-5 are used for evaluation and the rest are used for training.

Split 999 is deprecated, please use 0,1,2,3 instead. More details can be found in dataset.py.
