### ISSUE TITLE
为什么按照作者提供的代码训练之后，无法达到实验结果？ 

### ISSUE THREAD

**Issue by helix333111** [Jia-Research-Lab/PFENet#31]
以 resnet-v2 为backbone，split=0， epoch = 200 , 训练之后的结果远没有达到  mIoU 61.7（ pascal 5i 1shot fold 0）?

作者提供的模型可以达到61.7 ，是不是epoch 为200太少了，还是batch size 为4 太小了？

我的训练结果只有 mIoU 接近 50

请教各位同学。

**Comment by tianzhuotao** [comment]
@helix333111 
Hi, thanks for your interest.

You can take reference from this issue:

https://github.com/Jia-Research-Lab/PFENet/issues/6

We only use 1 GPU to train our model, and different Pytorch versions may cause different results.

Thank you.

**Comment by tianzhuotao** [comment]
@helix333111 

If you have any further questions, feel free to re-open this issue.

Thank you~

**Comment by helix333111** [comment]
Thank you !!
