### ISSUE TITLE
about coco-dataset

### ISSUE THREAD

**Issue by 1144181135** [Jia-Research-Lab/PFENet#32]
In the coco txt, I see the ".png" for annotations. How do you get the coco .png annotations? Thanks

**Comment by tianzhuotao** [comment]
@1144181135 

Hi, we have provided the script at [Onedrive](https://github.com/Jia-Research-Lab/PFENet/issues/20).

Thanks for your interest.

**Comment by heaven-01** [comment]
@tianzhuotao ,he script of this link was modified on 2021/6/21,please provide the new one,thanks.
