### ISSUE TITLE
Can not download pretrained model

### ISSUE THREAD

**Issue by jingliang95** [Jia-Research-Lab/PFENet#4]
The pretrained model cannot be downloaded from the given link: https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/EW20i_eiTINDgJDqUqikNR4Bo-7kVFkLBkxGZ2_uorOJcw?e=4%3aSIRlwD&at=9

**Comment by SmalWhite** [comment]
用迅雷下

**Comment by achenzx** [comment]
@jingliang95 I can access this link and perhaps you should use a proxy/better downloader as suggested by @SmalWhite  to use OneDrive for faster downloading speed.

**Comment by tianzhuotao** [comment]
@jingliang95  If you have further questions please let me know. Thank you.

**Comment by qiulesun** [comment]
@achenzx 
The released resnet50_v2 model is trained from scratch by yourself with dilation conv (dilation rate=2,4 for layer3 and layer4) ?

**Comment by tianzhuotao** [comment]
@qiulesun Hi, 

1. The ResNet we directly use the ones provided by PSPNet Pytorch (https://github.com/hszhao/semseg). 

2. This repo supports COCO training, but it takes a much longer time to train. 

3. Yes, there are some redundant lines. Sorry for the inconvenience.
