### ISSUE TITLE
the meaning of "split_gap" in function "validate".

### ISSUE THREAD

**Issue by SmalWhite** [Jia-Research-Lab/PFENet#5]
`for i in range(split_gap):
        logger.info('Class_{} Result: iou {:.4f}.'.format(i+1, class_iou_class[i]))    `
just split data into different group, but the class is not the split_gap range index.

**Comment by achenzx** [comment]
@SmalWhite Thanks for your interest. In a few-shot segmentation task, the class-wise accuracy is not measured, therefore the indexes within the split_gap range are only for the classes in the current data split, rather than the absolute class indexes.
