### ISSUE TITLE
sbd_data.txt

### ISSUE THREAD

**Issue by Sunbaoquan** [Jia-Research-Lab/PFENet#60]
Hi, how did you get the 5623 records in sbd_data.txt?

**Comment by Edithhhh** [comment]
Sorry, this problem I also did not solve, and did not continue to explore further.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月7日(星期四) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [dvlab-research/PFENet] sbd_data.txt (Issue #60)





 
Hi, do you now know how sbd_data.txt was obtained?
