### ISSUE TITLE
scripts for processing coco dataset

### ISSUE THREAD

**Issue by jingliang95** [Jia-Research-Lab/PFENet#8]
It is written that pair "image_path_1 label_path_1" is needed for training the network. But the annotation downloaded from coco is in .json format. May I ask if you can provide the script to generate semantic segmentation masks in .png from coco .json annotation?

Thanks

**Comment by achenzx** [comment]
Hi,

Please download the parsing script at [**OneDrive**](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155122171_link_cuhk_edu_hk/ETkX1jKVuJpAjpS2dk8XRhgBxkOUregKv4C7zigqFXiEtQ).

Thank you.

Best,
Zhuotao

**Comment by qiulesun** [comment]
@tianzhuotao 
Are the train/val lists for COCO and PACAL-5^i in list dir (e.g., lists/coco/train_data_list.txt) created by yourself ?
